name: trello2miro

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  equatable: ^1.2.5
  get_it: ^5.0.3
  http: ^0.12.2
  injectable: ^1.0.7
  json_annotation: ^3.1.1
  optional: ^5.0.0+1

dev_dependencies:
  build_runner: ^1.10.12
  injectable_generator: ^1.0.7
  json_serializable: ^3.5.1
  pedantic: ^1.9.0
  test: ^1.14.4
